#!/bin/bash
# Generates Aerio/BuildInfo.swift with the current git state so the running app
# can show which version it is (sidebar bottom row + tooltip).
#
# Used by:
#   - scripts/run.sh (local Release build + launch)
#   - .github/workflows/release.yml (tagged releases)
#   - .github/workflows/test.yml (CI tests, so build info compiles consistently)
#
# Args / env (optional):
#   BUILDINFO_BRANCH  — override branch name (CI typically passes tag name like "v1.2.3")
#   BUILDINFO_VERSION — override marketing version (CI release passes tag without "v")
set -e

cd "$(dirname "$0")/.."

GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=${BUILDINFO_BRANCH:-$(git branch --show-current 2>/dev/null || echo "unknown")}
# Branch may be empty in detached-HEAD CI checkouts; fall back to the ref or "detached".
if [ -z "$GIT_BRANCH" ]; then
    GIT_BRANCH=${GITHUB_REF_NAME:-detached}
fi

# Marketing version: explicit override (CI), then latest tag stripped of "v", then "0.0.0".
if [ -n "$BUILDINFO_VERSION" ]; then
    GIT_VERSION="$BUILDINFO_VERSION"
else
    GIT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
    [ -z "$GIT_VERSION" ] && GIT_VERSION="0.0.0"
fi

BUILD_DATE=$(date -u "+%Y-%m-%d %H:%M UTC")

cat > Aerio/BuildInfo.swift <<EOF
import Foundation

/// Generated by \`scripts/gen-buildinfo.sh\` before each build.
/// Edit values manually only if running xcodebuild without the script.
enum BuildInfo {
    static let version = "$GIT_VERSION"
    static let commit = "$GIT_SHA"
    static let branch = "$GIT_BRANCH"
    static let date = "$BUILD_DATE"

    static var shortLabel: String {
        "v\\(version) · \\(commit)"
    }
}
EOF

echo "Generated BuildInfo.swift: v$GIT_VERSION @ $GIT_SHA on $GIT_BRANCH ($BUILD_DATE)"
