#!/bin/bash
# Build, deploy, and run Aerio
set -e

cd "$(dirname "$0")/.."

OAUTH_CLIENT_ID=$(grep OAUTH_CLIENT_ID Aerio/Config/OAuth.local.xcconfig | cut -d= -f2 | tr -d ' ')

# Generate BuildInfo.swift with current git state so the running app shows
# which version it is (visible in the sidebar bottom row).
GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")
cat > Aerio/BuildInfo.swift <<EOF
import Foundation

/// Generated by \`scripts/run.sh\` before each build.
/// Edit values manually only if running xcodebuild without the script.
enum BuildInfo {
    static let commit = "$GIT_SHA"
    static let branch = "$GIT_BRANCH"
    static let date = "$BUILD_DATE"

    static var shortLabel: String {
        "\\(branch) · \\(commit)"
    }
}
EOF

pkill -x Aerio 2>/dev/null || true
sleep 0.5

xcodebuild -project Aerio.xcodeproj -scheme Aerio -configuration Release \
    -derivedDataPath build \
    OAUTH_CLIENT_ID="$OAUTH_CLIENT_ID" \
    build 2>&1 | tail -3

rm -rf /Applications/Aerio.app
cp -R build/Build/Products/Release/Aerio.app /Applications/Aerio.app
rm -rf build/Build/Products/Release/Aerio.app
open /Applications/Aerio.app

echo "✓ Aerio deployed and launched"
