import Foundation

/// Generated by `scripts/run.sh` before each build.
/// Edit values manually only if running xcodebuild without the script.
enum BuildInfo {
    static let commit = "50f4768"
    static let branch = "feat/outbox-reliable-send"
    static let date = "2026-05-08 07:16"

    static var shortLabel: String {
        "\(branch) · \(commit)"
    }
}
