import Foundation

/// Generated by `scripts/gen-buildinfo.sh` before each build.
/// Edit values manually only if running xcodebuild without the script.
enum BuildInfo {
    static let version = "1.5.0"
    static let commit = "83302f5"
    static let branch = "main"
    static let date = "2026-05-08 07:56 UTC"

    static var shortLabel: String {
        "v\(version) · \(commit)"
    }
}
